### ISSUE TITLE
2.0 roadmap

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/new-work#10]
- [ ] update UI, #9
- [ ] support screenshots, #7 
- [ ] move lockfiles to `~/.newwork` dir, #8 
- [ ] optimize speed (more aggressive caching?)
- [ ] on first `new-work` run, race request & headless and see which one is necessary. mark in lockfile, from then on, only periodically update screenshot (and make screenshots optional)
- [ ] refactor and update tests
- [x] fix errors and warnings by switching to event emitter pattern
- [ ] add auto-crawler? #12
